package com.seasac.pair.UI.GroupMenu

fun showGroupMainMenu() {
    println("┌────────────────────────────────────────────────────────────┐")
    print("│")
    print(String.format("%30s","그룹관리"))
    println(String.format("%28s","│"))
    println("├────────────────────────────────────────────────────────────┤")
    print("│")
    print(String.format("%31s","1 그룹목록"))
    println(String.format("%27s","│"))
    print("│")
    print(String.format("%31s","2 그룹등록"))
    println(String.format("%27s","│"))
    print("│")
    print(String.format("%31s","3 그룹검색"))
    println(String.format("%27s","│"))
    print("│")
    print(String.format("%31s","4 그룹수정"))
    println(String.format("%27s","│"))
    print("│")
    print(String.format("%31s","5 그룹삭제"))
    println(String.format("%27s","│"))
    println("└────────────────────────────────────────────────────────────┘")
}